{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2385edc8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import mysql.connector\n",
    "import pandas as pd\n",
    "from sqlalchemy import create_engine, types"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8cdc1428",
   "metadata": {},
   "outputs": [],
   "source": [
    "engine = create_engine(\"mysql://root:19961999@localhost:3306/nas\") #connecting to the database\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7240cf3b",
   "metadata": {},
   "outputs": [],
   "source": [
    "connection=engine.connect()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "83d678ca",
   "metadata": {},
   "outputs": [],
   "source": [
    "file_names = [\"customers\", \"categories\",\"Geolocation\", \"orders\", \"Order Items\",\n",
    "             \"Order Payments\", \"Products\", \"Reviews\",\"Sellers\"] #file and table names"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "426db2f8",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\nasrn\\anaconda3\\lib\\site-packages\\pandas\\io\\sql.py:1666: UserWarning: The provided table name 'Order_Items' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  warnings.warn(msg, UserWarning)\n",
      "C:\\Users\\nasrn\\anaconda3\\lib\\site-packages\\pandas\\io\\sql.py:1666: UserWarning: The provided table name 'Order_Payments' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  warnings.warn(msg, UserWarning)\n",
      "C:\\Users\\nasrn\\anaconda3\\lib\\site-packages\\pandas\\io\\sql.py:1666: UserWarning: The provided table name 'Products' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  warnings.warn(msg, UserWarning)\n",
      "C:\\Users\\nasrn\\anaconda3\\lib\\site-packages\\pandas\\io\\sql.py:1666: UserWarning: The provided table name 'Reviews' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  warnings.warn(msg, UserWarning)\n",
      "C:\\Users\\nasrn\\anaconda3\\lib\\site-packages\\pandas\\io\\sql.py:1666: UserWarning: The provided table name 'Sellers' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  warnings.warn(msg, UserWarning)\n",
      "C:\\Users\\nasrn\\anaconda3\\lib\\site-packages\\pandas\\io\\sql.py:1666: UserWarning: The provided table name 'Geolocation' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.\n",
      "  warnings.warn(msg, UserWarning)\n"
     ]
    }
   ],
   "source": [
    "for file in file_names:\n",
    "    csv_file = file+\".csv\"\n",
    "    table_name = file.replace(\" \",\"_\")\n",
    "    df = pd.read_csv(csv_file)\n",
    "    df.to_sql(table_name,con=engine,index=False,if_exists='append')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "450459db",
   "metadata": {},
   "outputs": [],
   "source": [
    "connection.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "0b78d4ec",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0bda703d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
